# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82f3ef2c4079e7e489c2b32490dcdaf430df244e1cdde87d83930734b4eca69f9822682fb4921ec08ddef9fa83a441157c7aaa915681391c2b1780eb8f1dd8ec

test:
  secret_key_base: 06c7725408f83e7c8a5e9565915fba19e3afda7cc0a8e631a8f84205c9c38280a448fd434c99862fd25e977af7da74266403bc56991afc61606b2e077695a7f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
